language: python

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.39/hugo_0.39_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - pip install Pygments

script:
  - hugo

deploy:
  local_dir: public
  repo: matthieugouel/matthieugouel.github.io 
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: matthieu.gouel@gmail.com
  name: "matthieugouel"
  on:
    branch: master
